# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'plot_controller.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from qtpy.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from qtpy.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from qtpy.QtWidgets import (QApplication, QButtonGroup, QComboBox, QFrame,
    QGridLayout, QGroupBox, QHBoxLayout, QLCDNumber,
    QLabel, QPushButton, QRadioButton, QSizePolicy,
    QSlider, QSpacerItem, QSplitter, QTabWidget,
    QToolButton, QVBoxLayout, QWidget)

from gui.resources.widgets.variable_from_to_scale_widget import variable_from_to_scale_widget

class Ui_plotController(object):
    def setupUi(self, plotController):
        if not plotController.objectName():
            plotController.setObjectName(u"plotController")
        plotController.resize(422, 504)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(plotController.sizePolicy().hasHeightForWidth())
        plotController.setSizePolicy(sizePolicy)
        plotController.setCursor(QCursor(Qt.CursorShape.IBeamCursor))
        self.action1x = QAction(plotController)
        self.action1x.setObjectName(u"action1x")
        self.action1x.setMenuRole(QAction.MenuRole.NoRole)
        self.verticalLayout_4 = QVBoxLayout(plotController)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.plotSettingsTabs = QTabWidget(plotController)
        self.plotSettingsTabs.setObjectName(u"plotSettingsTabs")
        sizePolicy.setHeightForWidth(self.plotSettingsTabs.sizePolicy().hasHeightForWidth())
        self.plotSettingsTabs.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(12)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.plotSettingsTabs.setFont(font)
        self.plotSettingsTabs.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.plotSettingsTabs.setUsesScrollButtons(False)
        self.plot3d_tab = QWidget()
        self.plot3d_tab.setObjectName(u"plot3d_tab")
        sizePolicy.setHeightForWidth(self.plot3d_tab.sizePolicy().hasHeightForWidth())
        self.plot3d_tab.setSizePolicy(sizePolicy)
        self.verticalLayout = QVBoxLayout(self.plot3d_tab)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.splitter_4 = QSplitter(self.plot3d_tab)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setOrientation(Qt.Orientation.Vertical)
        self.splitter_8 = QSplitter(self.splitter_4)
        self.splitter_8.setObjectName(u"splitter_8")
        self.splitter_8.setOrientation(Qt.Orientation.Horizontal)
        self.plot_state_grid3D_l = QLabel(self.splitter_8)
        self.plot_state_grid3D_l.setObjectName(u"plot_state_grid3D_l")
        sizePolicy.setHeightForWidth(self.plot_state_grid3D_l.sizePolicy().hasHeightForWidth())
        self.plot_state_grid3D_l.setSizePolicy(sizePolicy)
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setStrikeOut(False)
        font1.setKerning(False)
        self.plot_state_grid3D_l.setFont(font1)
        self.splitter_8.addWidget(self.plot_state_grid3D_l)
        self.plot_state_grid3D = QComboBox(self.splitter_8)
        self.plot_state_grid3D.setObjectName(u"plot_state_grid3D")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(2)
        sizePolicy1.setVerticalStretch(1)
        sizePolicy1.setHeightForWidth(self.plot_state_grid3D.sizePolicy().hasHeightForWidth())
        self.plot_state_grid3D.setSizePolicy(sizePolicy1)
        self.splitter_8.addWidget(self.plot_state_grid3D)
        self.splitter_4.addWidget(self.splitter_8)
        self.line = QFrame(self.splitter_4)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.splitter_4.addWidget(self.line)

        self.verticalLayout.addWidget(self.splitter_4)

        self.xAxis_l = QLabel(self.plot3d_tab)
        self.xAxis_l.setObjectName(u"xAxis_l")
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        font2.setStrikeOut(False)
        font2.setKerning(True)
        self.xAxis_l.setFont(font2)

        self.verticalLayout.addWidget(self.xAxis_l)

        self.xAxisGridPlotOptions = variable_from_to_scale_widget(self.plot3d_tab)
        self.xAxisGridPlotOptions.setObjectName(u"xAxisGridPlotOptions")
        sizePolicy.setHeightForWidth(self.xAxisGridPlotOptions.sizePolicy().hasHeightForWidth())
        self.xAxisGridPlotOptions.setSizePolicy(sizePolicy)
        self.xAxisGridPlotOptions.setFrameShape(QFrame.Shape.StyledPanel)
        self.xAxisGridPlotOptions.setFrameShadow(QFrame.Shadow.Raised)
        self.xAxisGridPlotOptions.setProperty("toEntryDefault", 0.000000000000000)
        self.xAxisGridPlotOptions.setProperty("fromEntryDefault", 0.000000000000000)
        self.xAxisGridPlotOptions.setProperty("variableMax", 0.000000000000000)
        self.xAxisGridPlotOptions.setProperty("variableMin", 0.000000000000000)
        self.xAxisGridPlotOptions.setProperty("variableDecimals", 0.000000000000000)

        self.verticalLayout.addWidget(self.xAxisGridPlotOptions)

        self.yAxis_l = QLabel(self.plot3d_tab)
        self.yAxis_l.setObjectName(u"yAxis_l")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(1)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.yAxis_l.sizePolicy().hasHeightForWidth())
        self.yAxis_l.setSizePolicy(sizePolicy2)
        self.yAxis_l.setFont(font2)

        self.verticalLayout.addWidget(self.yAxis_l)

        self.yAxisGridPlotOptions = variable_from_to_scale_widget(self.plot3d_tab)
        self.yAxisGridPlotOptions.setObjectName(u"yAxisGridPlotOptions")
        sizePolicy.setHeightForWidth(self.yAxisGridPlotOptions.sizePolicy().hasHeightForWidth())
        self.yAxisGridPlotOptions.setSizePolicy(sizePolicy)
        self.yAxisGridPlotOptions.setFrameShape(QFrame.Shape.StyledPanel)
        self.yAxisGridPlotOptions.setFrameShadow(QFrame.Shadow.Raised)
        self.yAxisGridPlotOptions.setProperty("toEntryDefault", 0.000000000000000)
        self.yAxisGridPlotOptions.setProperty("fromEntryDefault", 0.000000000000000)
        self.yAxisGridPlotOptions.setProperty("variableMax", 0.000000000000000)
        self.yAxisGridPlotOptions.setProperty("variableMin", 0.000000000000000)
        self.yAxisGridPlotOptions.setProperty("variableDecimals", 0.000000000000000)

        self.verticalLayout.addWidget(self.yAxisGridPlotOptions)

        self.zAxis_l = QLabel(self.plot3d_tab)
        self.zAxis_l.setObjectName(u"zAxis_l")
        self.zAxis_l.setFont(font2)

        self.verticalLayout.addWidget(self.zAxis_l)

        self.zAxisGridPlotOptions = variable_from_to_scale_widget(self.plot3d_tab)
        self.zAxisGridPlotOptions.setObjectName(u"zAxisGridPlotOptions")
        sizePolicy.setHeightForWidth(self.zAxisGridPlotOptions.sizePolicy().hasHeightForWidth())
        self.zAxisGridPlotOptions.setSizePolicy(sizePolicy)
        self.zAxisGridPlotOptions.setFrameShape(QFrame.Shape.StyledPanel)
        self.zAxisGridPlotOptions.setFrameShadow(QFrame.Shadow.Raised)
        self.zAxisGridPlotOptions.setProperty("toEntryDefault", 0.000000000000000)
        self.zAxisGridPlotOptions.setProperty("fromEntryDefault", 0.000000000000000)
        self.zAxisGridPlotOptions.setProperty("variableMax", 0.000000000000000)
        self.zAxisGridPlotOptions.setProperty("variableMin", 0.000000000000000)
        self.zAxisGridPlotOptions.setProperty("variableDecimals", 0.000000000000000)

        self.verticalLayout.addWidget(self.zAxisGridPlotOptions)

        self.freqSelect_f = QFrame(self.plot3d_tab)
        self.freqSelect_f.setObjectName(u"freqSelect_f")
        font3 = QFont()
        font3.setPointSize(12)
        font3.setStrikeOut(False)
        font3.setKerning(True)
        self.freqSelect_f.setFont(font3)
        self.freqSelect_f.setFrameShape(QFrame.Shape.StyledPanel)
        self.freqSelect_f.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.freqSelect_f)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(-1, 1, -1, 1)
        self.frequency_l = QLabel(self.freqSelect_f)
        self.frequency_l.setObjectName(u"frequency_l")
        self.frequency_l.setFont(font3)

        self.horizontalLayout_2.addWidget(self.frequency_l)

        self.frequency_slider = QSlider(self.freqSelect_f)
        self.frequency_slider.setObjectName(u"frequency_slider")
        self.frequency_slider.setOrientation(Qt.Orientation.Horizontal)
        self.frequency_slider.setTickPosition(QSlider.TickPosition.TicksBelow)

        self.horizontalLayout_2.addWidget(self.frequency_slider)

        self.currentFrequency_l = QLCDNumber(self.freqSelect_f)
        self.currentFrequency_l.setObjectName(u"currentFrequency_l")
        self.currentFrequency_l.setSmallDecimalPoint(True)
        self.currentFrequency_l.setDigitCount(6)
        self.currentFrequency_l.setProperty("value", 0.000000000000000)

        self.horizontalLayout_2.addWidget(self.currentFrequency_l)


        self.verticalLayout.addWidget(self.freqSelect_f)

        self.plotCommands_f = QFrame(self.plot3d_tab)
        self.plotCommands_f.setObjectName(u"plotCommands_f")
        self.plotCommands_f.setFrameShape(QFrame.Shape.StyledPanel)
        self.plotCommands_f.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.plotCommands_f)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(-1, 2, -1, 2)

        self.verticalLayout.addWidget(self.plotCommands_f)

        self.verticalSpacer_3 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer_3)

        self.updatePlot_button = QPushButton(self.plot3d_tab)
        self.updatePlot_button.setObjectName(u"updatePlot_button")
        self.updatePlot_button.setFont(font3)

        self.verticalLayout.addWidget(self.updatePlot_button)

        self.plotSettingsTabs.addTab(self.plot3d_tab, "")
        self.timeHistory3D_tab = QWidget()
        self.timeHistory3D_tab.setObjectName(u"timeHistory3D_tab")
        sizePolicy.setHeightForWidth(self.timeHistory3D_tab.sizePolicy().hasHeightForWidth())
        self.timeHistory3D_tab.setSizePolicy(sizePolicy)
        self.verticalLayout_3 = QVBoxLayout(self.timeHistory3D_tab)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.splitter_5 = QSplitter(self.timeHistory3D_tab)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setOrientation(Qt.Orientation.Horizontal)
        self.plot_state_time3D_l = QLabel(self.splitter_5)
        self.plot_state_time3D_l.setObjectName(u"plot_state_time3D_l")
        sizePolicy.setHeightForWidth(self.plot_state_time3D_l.sizePolicy().hasHeightForWidth())
        self.plot_state_time3D_l.setSizePolicy(sizePolicy)
        self.plot_state_time3D_l.setFont(font1)
        self.splitter_5.addWidget(self.plot_state_time3D_l)
        self.plot_state_time3D = QComboBox(self.splitter_5)
        self.plot_state_time3D.setObjectName(u"plot_state_time3D")
        sizePolicy1.setHeightForWidth(self.plot_state_time3D.sizePolicy().hasHeightForWidth())
        self.plot_state_time3D.setSizePolicy(sizePolicy1)
        self.splitter_5.addWidget(self.plot_state_time3D)

        self.verticalLayout_3.addWidget(self.splitter_5)

        self.line_2 = QFrame(self.timeHistory3D_tab)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayout_3.addWidget(self.line_2)

        self.paramAxis_l = QLabel(self.timeHistory3D_tab)
        self.paramAxis_l.setObjectName(u"paramAxis_l")
        sizePolicy2.setHeightForWidth(self.paramAxis_l.sizePolicy().hasHeightForWidth())
        self.paramAxis_l.setSizePolicy(sizePolicy2)
        self.paramAxis_l.setFont(font2)

        self.verticalLayout_3.addWidget(self.paramAxis_l)

        self.progressionVarTime_options = variable_from_to_scale_widget(self.timeHistory3D_tab)
        self.progressionVarTime_options.setObjectName(u"progressionVarTime_options")
        sizePolicy.setHeightForWidth(self.progressionVarTime_options.sizePolicy().hasHeightForWidth())
        self.progressionVarTime_options.setSizePolicy(sizePolicy)
        self.progressionVarTime_options.setMinimumSize(QSize(0, 10))
        self.progressionVarTime_options.setFrameShape(QFrame.Shape.StyledPanel)
        self.progressionVarTime_options.setFrameShadow(QFrame.Shadow.Raised)
        self.progressionVarTime_options.setProperty("variableMax", 0.000000000000000)
        self.progressionVarTime_options.setProperty("variableMin", 0.000000000000000)
        self.progressionVarTime_options.setProperty("variableDecimals", 0.000000000000000)
        self.progressionVarTime_options.setProperty("fromEntryDefault", 0.000000000000000)
        self.progressionVarTime_options.setProperty("toEntryDefault", 0.000000000000000)

        self.verticalLayout_3.addWidget(self.progressionVarTime_options)

        self.timeAxis_l = QLabel(self.timeHistory3D_tab)
        self.timeAxis_l.setObjectName(u"timeAxis_l")
        sizePolicy2.setHeightForWidth(self.timeAxis_l.sizePolicy().hasHeightForWidth())
        self.timeAxis_l.setSizePolicy(sizePolicy2)
        self.timeAxis_l.setFont(font2)

        self.verticalLayout_3.addWidget(self.timeAxis_l)

        self.timeAxis3d_options = variable_from_to_scale_widget(self.timeHistory3D_tab)
        self.timeAxis3d_options.setObjectName(u"timeAxis3d_options")
        sizePolicy.setHeightForWidth(self.timeAxis3d_options.sizePolicy().hasHeightForWidth())
        self.timeAxis3d_options.setSizePolicy(sizePolicy)
        self.timeAxis3d_options.setMinimumSize(QSize(0, 10))
        self.timeAxis3d_options.setFrameShape(QFrame.Shape.StyledPanel)
        self.timeAxis3d_options.setFrameShadow(QFrame.Shadow.Raised)
        self.timeAxis3d_options.setProperty("variableMax", 0.000000000000000)
        self.timeAxis3d_options.setProperty("variableMin", 0.000000000000000)
        self.timeAxis3d_options.setProperty("variableDecimals", 0.000000000000000)
        self.timeAxis3d_options.setProperty("fromEntryDefault", 0.000000000000000)
        self.timeAxis3d_options.setProperty("toEntryDefault", 0.000000000000000)

        self.verticalLayout_3.addWidget(self.timeAxis3d_options)

        self.amplAxis_l = QLabel(self.timeHistory3D_tab)
        self.amplAxis_l.setObjectName(u"amplAxis_l")
        self.amplAxis_l.setFont(font2)

        self.verticalLayout_3.addWidget(self.amplAxis_l)

        self.amplAxisTime3d_options = variable_from_to_scale_widget(self.timeHistory3D_tab)
        self.amplAxisTime3d_options.setObjectName(u"amplAxisTime3d_options")
        sizePolicy.setHeightForWidth(self.amplAxisTime3d_options.sizePolicy().hasHeightForWidth())
        self.amplAxisTime3d_options.setSizePolicy(sizePolicy)
        self.amplAxisTime3d_options.setMinimumSize(QSize(0, 10))
        self.amplAxisTime3d_options.setFrameShape(QFrame.Shape.StyledPanel)
        self.amplAxisTime3d_options.setFrameShadow(QFrame.Shadow.Raised)
        self.amplAxisTime3d_options.setProperty("variableMax", 0.000000000000000)
        self.amplAxisTime3d_options.setProperty("variableMin", 0.000000000000000)
        self.amplAxisTime3d_options.setProperty("variableDecimals", 0.000000000000000)
        self.amplAxisTime3d_options.setProperty("fromEntryDefault", 0.000000000000000)
        self.amplAxisTime3d_options.setProperty("toEntryDefault", 0.000000000000000)

        self.verticalLayout_3.addWidget(self.amplAxisTime3d_options)

        self.fixedParamSelectTime_f = QFrame(self.timeHistory3D_tab)
        self.fixedParamSelectTime_f.setObjectName(u"fixedParamSelectTime_f")
        self.fixedParamSelectTime_f.setFont(font3)
        self.fixedParamSelectTime_f.setFrameShape(QFrame.Shape.StyledPanel)
        self.fixedParamSelectTime_f.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.fixedParamSelectTime_f)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(-1, 1, -1, 1)
        self.fixedParamTime_l = QLabel(self.fixedParamSelectTime_f)
        self.fixedParamTime_l.setObjectName(u"fixedParamTime_l")
        self.fixedParamTime_l.setFont(font3)

        self.horizontalLayout_4.addWidget(self.fixedParamTime_l)

        self.fixedParamTime_slider = QSlider(self.fixedParamSelectTime_f)
        self.fixedParamTime_slider.setObjectName(u"fixedParamTime_slider")
        self.fixedParamTime_slider.setOrientation(Qt.Orientation.Horizontal)

        self.horizontalLayout_4.addWidget(self.fixedParamTime_slider)

        self.fixedParamTime_display = QLCDNumber(self.fixedParamSelectTime_f)
        self.fixedParamTime_display.setObjectName(u"fixedParamTime_display")
        self.fixedParamTime_display.setSmallDecimalPoint(True)
        self.fixedParamTime_display.setDigitCount(6)

        self.horizontalLayout_4.addWidget(self.fixedParamTime_display)

        self.fixedParamTimeAnimate_button = QToolButton(self.fixedParamSelectTime_f)
        self.fixedParamTimeAnimate_button.setObjectName(u"fixedParamTimeAnimate_button")
        self.fixedParamTimeAnimate_button.setPopupMode(QToolButton.ToolButtonPopupMode.MenuButtonPopup)
        self.fixedParamTimeAnimate_button.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.fixedParamTimeAnimate_button.setAutoRaise(False)
        self.fixedParamTimeAnimate_button.setArrowType(Qt.ArrowType.NoArrow)

        self.horizontalLayout_4.addWidget(self.fixedParamTimeAnimate_button)


        self.verticalLayout_3.addWidget(self.fixedParamSelectTime_f)

        self.verticalSpacer_4 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_3.addItem(self.verticalSpacer_4)

        self.updatePlot_button_2 = QPushButton(self.timeHistory3D_tab)
        self.updatePlot_button_2.setObjectName(u"updatePlot_button_2")
        self.updatePlot_button_2.setFont(font3)

        self.verticalLayout_3.addWidget(self.updatePlot_button_2)

        self.plotSettingsTabs.addTab(self.timeHistory3D_tab, "")
        self.spectrogram3d_tab = QWidget()
        self.spectrogram3d_tab.setObjectName(u"spectrogram3d_tab")
        sizePolicy.setHeightForWidth(self.spectrogram3d_tab.sizePolicy().hasHeightForWidth())
        self.spectrogram3d_tab.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QVBoxLayout(self.spectrogram3d_tab)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.splitter_6 = QSplitter(self.spectrogram3d_tab)
        self.splitter_6.setObjectName(u"splitter_6")
        self.splitter_6.setOrientation(Qt.Orientation.Vertical)
        self.splitter_7 = QSplitter(self.splitter_6)
        self.splitter_7.setObjectName(u"splitter_7")
        self.splitter_7.setOrientation(Qt.Orientation.Horizontal)
        self.plot_state_spec3D_2 = QLabel(self.splitter_7)
        self.plot_state_spec3D_2.setObjectName(u"plot_state_spec3D_2")
        sizePolicy.setHeightForWidth(self.plot_state_spec3D_2.sizePolicy().hasHeightForWidth())
        self.plot_state_spec3D_2.setSizePolicy(sizePolicy)
        self.plot_state_spec3D_2.setFont(font1)
        self.splitter_7.addWidget(self.plot_state_spec3D_2)
        self.plot_state_spec3D = QComboBox(self.splitter_7)
        self.plot_state_spec3D.setObjectName(u"plot_state_spec3D")
        sizePolicy1.setHeightForWidth(self.plot_state_spec3D.sizePolicy().hasHeightForWidth())
        self.plot_state_spec3D.setSizePolicy(sizePolicy1)
        self.splitter_7.addWidget(self.plot_state_spec3D)
        self.splitter_6.addWidget(self.splitter_7)
        self.line_3 = QFrame(self.splitter_6)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.splitter_6.addWidget(self.line_3)

        self.verticalLayout_2.addWidget(self.splitter_6)

        self.paramAxisSpec_l = QLabel(self.spectrogram3d_tab)
        self.paramAxisSpec_l.setObjectName(u"paramAxisSpec_l")
        sizePolicy2.setHeightForWidth(self.paramAxisSpec_l.sizePolicy().hasHeightForWidth())
        self.paramAxisSpec_l.setSizePolicy(sizePolicy2)
        self.paramAxisSpec_l.setFont(font2)

        self.verticalLayout_2.addWidget(self.paramAxisSpec_l)

        self.paramAxisSpec3d_options = variable_from_to_scale_widget(self.spectrogram3d_tab)
        self.paramAxisSpec3d_options.setObjectName(u"paramAxisSpec3d_options")
        sizePolicy.setHeightForWidth(self.paramAxisSpec3d_options.sizePolicy().hasHeightForWidth())
        self.paramAxisSpec3d_options.setSizePolicy(sizePolicy)
        self.paramAxisSpec3d_options.setMinimumSize(QSize(0, 10))
        self.paramAxisSpec3d_options.setFrameShape(QFrame.Shape.StyledPanel)
        self.paramAxisSpec3d_options.setFrameShadow(QFrame.Shadow.Raised)
        self.paramAxisSpec3d_options.setProperty("variableMin", 0.000000000000000)
        self.paramAxisSpec3d_options.setProperty("variableMax", 0.000000000000000)
        self.paramAxisSpec3d_options.setProperty("variableDecimals", 0.000000000000000)
        self.paramAxisSpec3d_options.setProperty("toEntryDefault", 0.000000000000000)
        self.paramAxisSpec3d_options.setProperty("fromEntryDefault", 0.000000000000000)

        self.verticalLayout_2.addWidget(self.paramAxisSpec3d_options)

        self.freqAxisSpec3d_l = QLabel(self.spectrogram3d_tab)
        self.freqAxisSpec3d_l.setObjectName(u"freqAxisSpec3d_l")
        self.freqAxisSpec3d_l.setFont(font2)

        self.verticalLayout_2.addWidget(self.freqAxisSpec3d_l)

        self.freqAxisSpec3d_options = variable_from_to_scale_widget(self.spectrogram3d_tab)
        self.freqAxisSpec3d_options.setObjectName(u"freqAxisSpec3d_options")
        sizePolicy.setHeightForWidth(self.freqAxisSpec3d_options.sizePolicy().hasHeightForWidth())
        self.freqAxisSpec3d_options.setSizePolicy(sizePolicy)
        self.freqAxisSpec3d_options.setMinimumSize(QSize(0, 10))
        self.freqAxisSpec3d_options.setFrameShape(QFrame.Shape.StyledPanel)
        self.freqAxisSpec3d_options.setFrameShadow(QFrame.Shadow.Raised)
        self.freqAxisSpec3d_options.setProperty("variableMin", 0.000000000000000)
        self.freqAxisSpec3d_options.setProperty("variableMax", 0.000000000000000)
        self.freqAxisSpec3d_options.setProperty("variableDecimals", 0.000000000000000)
        self.freqAxisSpec3d_options.setProperty("toEntryDefault", 0.000000000000000)
        self.freqAxisSpec3d_options.setProperty("fromEntryDefault", 0.000000000000000)

        self.verticalLayout_2.addWidget(self.freqAxisSpec3d_options)

        self.amplAxisSpec3d_l = QLabel(self.spectrogram3d_tab)
        self.amplAxisSpec3d_l.setObjectName(u"amplAxisSpec3d_l")
        sizePolicy2.setHeightForWidth(self.amplAxisSpec3d_l.sizePolicy().hasHeightForWidth())
        self.amplAxisSpec3d_l.setSizePolicy(sizePolicy2)
        self.amplAxisSpec3d_l.setFont(font2)

        self.verticalLayout_2.addWidget(self.amplAxisSpec3d_l)

        self.amplAxisSpec3d_options = variable_from_to_scale_widget(self.spectrogram3d_tab)
        self.amplAxisSpec3d_options.setObjectName(u"amplAxisSpec3d_options")
        sizePolicy.setHeightForWidth(self.amplAxisSpec3d_options.sizePolicy().hasHeightForWidth())
        self.amplAxisSpec3d_options.setSizePolicy(sizePolicy)
        self.amplAxisSpec3d_options.setMinimumSize(QSize(0, 10))
        self.amplAxisSpec3d_options.setFrameShape(QFrame.Shape.StyledPanel)
        self.amplAxisSpec3d_options.setFrameShadow(QFrame.Shadow.Raised)
        self.amplAxisSpec3d_options.setProperty("variableMin", 0.000000000000000)
        self.amplAxisSpec3d_options.setProperty("variableMax", 0.000000000000000)
        self.amplAxisSpec3d_options.setProperty("variableDecimals", 0.000000000000000)
        self.amplAxisSpec3d_options.setProperty("toEntryDefault", 0.000000000000000)
        self.amplAxisSpec3d_options.setProperty("fromEntryDefault", 0.000000000000000)

        self.verticalLayout_2.addWidget(self.amplAxisSpec3d_options)

        self.fixedParamSelectTime_f_2 = QFrame(self.spectrogram3d_tab)
        self.fixedParamSelectTime_f_2.setObjectName(u"fixedParamSelectTime_f_2")
        self.fixedParamSelectTime_f_2.setFont(font3)
        self.fixedParamSelectTime_f_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.fixedParamSelectTime_f_2.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.fixedParamSelectTime_f_2)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(-1, 1, -1, 1)
        self.fixedParamSpec_l = QLabel(self.fixedParamSelectTime_f_2)
        self.fixedParamSpec_l.setObjectName(u"fixedParamSpec_l")
        self.fixedParamSpec_l.setFont(font3)

        self.horizontalLayout_5.addWidget(self.fixedParamSpec_l)

        self.fixedParamSpec_slider = QSlider(self.fixedParamSelectTime_f_2)
        self.fixedParamSpec_slider.setObjectName(u"fixedParamSpec_slider")
        self.fixedParamSpec_slider.setOrientation(Qt.Orientation.Horizontal)

        self.horizontalLayout_5.addWidget(self.fixedParamSpec_slider)

        self.fixedParamSpec_display = QLCDNumber(self.fixedParamSelectTime_f_2)
        self.fixedParamSpec_display.setObjectName(u"fixedParamSpec_display")
        self.fixedParamSpec_display.setSmallDecimalPoint(True)
        self.fixedParamSpec_display.setDigitCount(6)

        self.horizontalLayout_5.addWidget(self.fixedParamSpec_display)

        self.fixedParamSpecAnimate_button = QToolButton(self.fixedParamSelectTime_f_2)
        self.fixedParamSpecAnimate_button.setObjectName(u"fixedParamSpecAnimate_button")
        self.fixedParamSpecAnimate_button.setPopupMode(QToolButton.ToolButtonPopupMode.MenuButtonPopup)
        self.fixedParamSpecAnimate_button.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.fixedParamSpecAnimate_button.setAutoRaise(False)
        self.fixedParamSpecAnimate_button.setArrowType(Qt.ArrowType.NoArrow)

        self.horizontalLayout_5.addWidget(self.fixedParamSpecAnimate_button)


        self.verticalLayout_2.addWidget(self.fixedParamSelectTime_f_2)

        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_2.addItem(self.verticalSpacer_2)

        self.updatePlot_button_3 = QPushButton(self.spectrogram3d_tab)
        self.updatePlot_button_3.setObjectName(u"updatePlot_button_3")
        self.updatePlot_button_3.setFont(font3)

        self.verticalLayout_2.addWidget(self.updatePlot_button_3)

        self.plotSettingsTabs.addTab(self.spectrogram3d_tab, "")
        self.plotSingle_tab = QWidget()
        self.plotSingle_tab.setObjectName(u"plotSingle_tab")
        sizePolicy.setHeightForWidth(self.plotSingle_tab.sizePolicy().hasHeightForWidth())
        self.plotSingle_tab.setSizePolicy(sizePolicy)
        self.verticalLayout_6 = QVBoxLayout(self.plotSingle_tab)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.splitter = QSplitter(self.plotSingle_tab)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Vertical)
        self.singlePlotStyle_box = QGroupBox(self.splitter)
        self.singlePlotStyle_box.setObjectName(u"singlePlotStyle_box")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Maximum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.singlePlotStyle_box.sizePolicy().hasHeightForWidth())
        self.singlePlotStyle_box.setSizePolicy(sizePolicy3)
        self.singlePlotStyle_box.setFont(font3)
        self.gridLayout_6 = QGridLayout(self.singlePlotStyle_box)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.singleSpectrogram_button = QRadioButton(self.singlePlotStyle_box)
        self.singlePlotStyle_buttons = QButtonGroup(plotController)
        self.singlePlotStyle_buttons.setObjectName(u"singlePlotStyle_buttons")
        self.singlePlotStyle_buttons.addButton(self.singleSpectrogram_button)
        self.singleSpectrogram_button.setObjectName(u"singleSpectrogram_button")
        self.singleSpectrogram_button.setFont(font3)

        self.gridLayout_6.addWidget(self.singleSpectrogram_button, 0, 2, 1, 1)

        self.singleTimeDomain_button = QRadioButton(self.singlePlotStyle_box)
        self.singlePlotStyle_buttons.addButton(self.singleTimeDomain_button)
        self.singleTimeDomain_button.setObjectName(u"singleTimeDomain_button")
        self.singleTimeDomain_button.setFont(font3)

        self.gridLayout_6.addWidget(self.singleTimeDomain_button, 0, 4, 1, 1)

        self.phase2d_button = QRadioButton(self.singlePlotStyle_box)
        self.singlePlotStyle_buttons.addButton(self.phase2d_button)
        self.phase2d_button.setObjectName(u"phase2d_button")

        self.gridLayout_6.addWidget(self.phase2d_button, 1, 2, 1, 1)

        self.phase3d_button = QRadioButton(self.singlePlotStyle_box)
        self.singlePlotStyle_buttons.addButton(self.phase3d_button)
        self.phase3d_button.setObjectName(u"phase3d_button")
        self.phase3d_button.setChecked(True)

        self.gridLayout_6.addWidget(self.phase3d_button, 1, 4, 1, 1)

        self.splitter.addWidget(self.singlePlotStyle_box)
        self.paramSelect_f = QFrame(self.splitter)
        self.paramSelect_f.setObjectName(u"paramSelect_f")
        sizePolicy3.setHeightForWidth(self.paramSelect_f.sizePolicy().hasHeightForWidth())
        self.paramSelect_f.setSizePolicy(sizePolicy3)
        self.paramSelect_f.setFrameShape(QFrame.Shape.StyledPanel)
        self.paramSelect_f.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_7 = QGridLayout(self.paramSelect_f)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.zAxisSinglePlotOptions = variable_from_to_scale_widget(self.paramSelect_f)
        self.zAxisSinglePlotOptions.setObjectName(u"zAxisSinglePlotOptions")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Expanding)
        sizePolicy4.setHorizontalStretch(1)
        sizePolicy4.setVerticalStretch(1)
        sizePolicy4.setHeightForWidth(self.zAxisSinglePlotOptions.sizePolicy().hasHeightForWidth())
        self.zAxisSinglePlotOptions.setSizePolicy(sizePolicy4)
        self.zAxisSinglePlotOptions.setFrameShape(QFrame.Shape.StyledPanel)
        self.zAxisSinglePlotOptions.setFrameShadow(QFrame.Shadow.Raised)
        self.zAxisSinglePlotOptions.setProperty("toEntryDefault", 0.000000000000000)
        self.zAxisSinglePlotOptions.setProperty("fromEntryDefault", 0.000000000000000)
        self.zAxisSinglePlotOptions.setProperty("variableMax", 0.000000000000000)
        self.zAxisSinglePlotOptions.setProperty("variableMin", 0.000000000000000)
        self.zAxisSinglePlotOptions.setProperty("variableDecimals", 0.000000000000000)

        self.gridLayout_7.addWidget(self.zAxisSinglePlotOptions, 8, 0, 1, 1)

        self.splitter_2 = QSplitter(self.paramSelect_f)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setOrientation(Qt.Orientation.Horizontal)
        self.param1Select_l = QLabel(self.splitter_2)
        self.param1Select_l.setObjectName(u"param1Select_l")
        self.param1Select_l.setFont(font3)
        self.splitter_2.addWidget(self.param1Select_l)
        self.param1ValSelect_dd = QComboBox(self.splitter_2)
        self.param1ValSelect_dd.setObjectName(u"param1ValSelect_dd")
        self.param1ValSelect_dd.setFont(font3)
        self.splitter_2.addWidget(self.param1ValSelect_dd)
        self.param1Animate_button = QToolButton(self.splitter_2)
        self.param1Animate_button.setObjectName(u"param1Animate_button")
        self.param1Animate_button.setPopupMode(QToolButton.ToolButtonPopupMode.MenuButtonPopup)
        self.param1Animate_button.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.param1Animate_button.setAutoRaise(False)
        self.param1Animate_button.setArrowType(Qt.ArrowType.NoArrow)
        self.splitter_2.addWidget(self.param1Animate_button)

        self.gridLayout_7.addWidget(self.splitter_2, 9, 0, 1, 1)

        self.yAxisSinglePlotOptions = variable_from_to_scale_widget(self.paramSelect_f)
        self.yAxisSinglePlotOptions.setObjectName(u"yAxisSinglePlotOptions")
        sizePolicy4.setHeightForWidth(self.yAxisSinglePlotOptions.sizePolicy().hasHeightForWidth())
        self.yAxisSinglePlotOptions.setSizePolicy(sizePolicy4)
        self.yAxisSinglePlotOptions.setFrameShape(QFrame.Shape.StyledPanel)
        self.yAxisSinglePlotOptions.setFrameShadow(QFrame.Shadow.Raised)
        self.yAxisSinglePlotOptions.setProperty("toEntryDefault", 0.000000000000000)
        self.yAxisSinglePlotOptions.setProperty("fromEntryDefault", 0.000000000000000)
        self.yAxisSinglePlotOptions.setProperty("variableMax", 0.000000000000000)
        self.yAxisSinglePlotOptions.setProperty("variableMin", 0.000000000000000)
        self.yAxisSinglePlotOptions.setProperty("variableDecimals", 0.000000000000000)

        self.gridLayout_7.addWidget(self.yAxisSinglePlotOptions, 6, 0, 1, 1)

        self.zAxis_l_2 = QLabel(self.paramSelect_f)
        self.zAxis_l_2.setObjectName(u"zAxis_l_2")
        sizePolicy4.setHeightForWidth(self.zAxis_l_2.sizePolicy().hasHeightForWidth())
        self.zAxis_l_2.setSizePolicy(sizePolicy4)
        self.zAxis_l_2.setFont(font2)

        self.gridLayout_7.addWidget(self.zAxis_l_2, 7, 0, 1, 1)

        self.xAxis_l_2 = QLabel(self.paramSelect_f)
        self.xAxis_l_2.setObjectName(u"xAxis_l_2")
        sizePolicy4.setHeightForWidth(self.xAxis_l_2.sizePolicy().hasHeightForWidth())
        self.xAxis_l_2.setSizePolicy(sizePolicy4)
        self.xAxis_l_2.setFont(font2)

        self.gridLayout_7.addWidget(self.xAxis_l_2, 0, 0, 1, 1)

        self.xAxisSinglePlotOptions = variable_from_to_scale_widget(self.paramSelect_f)
        self.xAxisSinglePlotOptions.setObjectName(u"xAxisSinglePlotOptions")
        sizePolicy4.setHeightForWidth(self.xAxisSinglePlotOptions.sizePolicy().hasHeightForWidth())
        self.xAxisSinglePlotOptions.setSizePolicy(sizePolicy4)
        self.xAxisSinglePlotOptions.setFrameShape(QFrame.Shape.StyledPanel)
        self.xAxisSinglePlotOptions.setFrameShadow(QFrame.Shadow.Raised)
        self.xAxisSinglePlotOptions.setProperty("toEntryDefault", 0.000000000000000)
        self.xAxisSinglePlotOptions.setProperty("fromEntryDefault", 0.000000000000000)
        self.xAxisSinglePlotOptions.setProperty("variableMax", 0.000000000000000)
        self.xAxisSinglePlotOptions.setProperty("variableMin", 0.000000000000000)
        self.xAxisSinglePlotOptions.setProperty("variableDecimals", 0.000000000000000)

        self.gridLayout_7.addWidget(self.xAxisSinglePlotOptions, 3, 0, 1, 1)

        self.yAxis_l_2 = QLabel(self.paramSelect_f)
        self.yAxis_l_2.setObjectName(u"yAxis_l_2")
        sizePolicy4.setHeightForWidth(self.yAxis_l_2.sizePolicy().hasHeightForWidth())
        self.yAxis_l_2.setSizePolicy(sizePolicy4)
        self.yAxis_l_2.setFont(font2)

        self.gridLayout_7.addWidget(self.yAxis_l_2, 5, 0, 1, 1)

        self.splitter_3 = QSplitter(self.paramSelect_f)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setOrientation(Qt.Orientation.Horizontal)
        self.Param2Select_l = QLabel(self.splitter_3)
        self.Param2Select_l.setObjectName(u"Param2Select_l")
        self.Param2Select_l.setFont(font3)
        self.splitter_3.addWidget(self.Param2Select_l)
        self.param2ValSelect_dd = QComboBox(self.splitter_3)
        self.param2ValSelect_dd.setObjectName(u"param2ValSelect_dd")
        self.param2ValSelect_dd.setFont(font3)
        self.splitter_3.addWidget(self.param2ValSelect_dd)
        self.param2Animate_button = QToolButton(self.splitter_3)
        self.param2Animate_button.setObjectName(u"param2Animate_button")
        self.param2Animate_button.setPopupMode(QToolButton.ToolButtonPopupMode.MenuButtonPopup)
        self.param2Animate_button.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.param2Animate_button.setAutoRaise(False)
        self.param2Animate_button.setArrowType(Qt.ArrowType.NoArrow)
        self.splitter_3.addWidget(self.param2Animate_button)

        self.gridLayout_7.addWidget(self.splitter_3, 10, 0, 1, 1)

        self.splitter.addWidget(self.paramSelect_f)

        self.verticalLayout_6.addWidget(self.splitter)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_6.addItem(self.verticalSpacer)

        self.updatePlot_button_4 = QPushButton(self.plotSingle_tab)
        self.updatePlot_button_4.setObjectName(u"updatePlot_button_4")
        self.updatePlot_button_4.setFont(font3)

        self.verticalLayout_6.addWidget(self.updatePlot_button_4)

        self.plotSettingsTabs.addTab(self.plotSingle_tab, "")

        self.verticalLayout_4.addWidget(self.plotSettingsTabs)


        self.retranslateUi(plotController)
        self.singlePlotStyle_buttons.buttonReleased.connect(plotController.update_singlePlotStyle)
        self.yAxisSinglePlotOptions.from_changed.connect(plotController.update_ySlice)
        self.yAxisGridPlotOptions.to_changed.connect(plotController.update_ySlice)
        self.updatePlot_button_4.released.connect(plotController.on_updatePlot)
        self.singleTimeDomain_button.clicked["bool"].connect(self.zAxisSinglePlotOptions.setVisible)
        self.amplAxisSpec3d_options.from_changed.connect(plotController.update_zSlice)
        self.xAxisSinglePlotOptions.from_changed.connect(plotController.update_xSlice)
        self.phase3d_button.clicked["bool"].connect(self.zAxisSinglePlotOptions.setHidden)
        self.updatePlot_button_3.released.connect(plotController.on_updatePlot)
        self.zAxisGridPlotOptions.to_changed.connect(plotController.update_zSlice)
        self.param2ValSelect_dd.currentIndexChanged.connect(plotController.select_single_param2)
        self.yAxisGridPlotOptions.scale_changed.connect(plotController.update_yScale)
        self.paramAxisSpec3d_options.scale_changed.connect(plotController.update_xScale)
        self.singleSpectrogram_button.clicked["bool"].connect(self.zAxisSinglePlotOptions.setVisible)
        self.xAxisGridPlotOptions.variable_changed.connect(plotController.update_xVar)
        self.progressionVarTime_options.from_changed.connect(plotController.update_xSlice)
        self.progressionVarTime_options.to_changed.connect(plotController.update_xSlice)
        self.amplAxisTime3d_options.to_changed.connect(plotController.update_zSlice)
        self.freqAxisSpec3d_options.scale_changed.connect(plotController.update_yScale)
        self.amplAxisSpec3d_options.variable_changed.connect(plotController.update_zVar)
        self.fixedParamSpec_slider.sliderMoved.connect(plotController.set_fixedParam)
        self.singleTimeDomain_button.clicked["bool"].connect(self.zAxis_l_2.setVisible)
        self.updatePlot_button_2.released.connect(plotController.on_updatePlot)
        self.xAxisGridPlotOptions.from_changed.connect(plotController.update_xSlice)
        self.paramAxisSpec3d_options.to_changed.connect(plotController.update_xSlice)
        self.amplAxisTime3d_options.from_changed.connect(plotController.update_zSlice)
        self.fixedParamSpecAnimate_button.released.connect(plotController.animate_fixedparam)
        self.timeAxis3d_options.to_changed.connect(plotController.update_ySlice)
        self.yAxisGridPlotOptions.from_changed.connect(plotController.update_ySlice)
        self.yAxisSinglePlotOptions.variable_changed.connect(plotController.update_yVar)
        self.param2Animate_button.released.connect(plotController.animate_param2_singleSet)
        self.freqAxisSpec3d_options.to_changed.connect(plotController.update_ySlice)
        self.phase3d_button.clicked["bool"].connect(self.zAxis_l_2.setHidden)
        self.fixedParamTime_slider.valueChanged.connect(plotController.set_fixedParam)
        self.fixedParamTimeAnimate_button.released.connect(plotController.animate_fixedparam)
        self.xAxisSinglePlotOptions.to_changed.connect(plotController.update_xSlice)
        self.amplAxisSpec3d_options.scale_changed.connect(plotController.update_zScale)
        self.frequency_slider.sliderMoved.connect(plotController.set_slice_frequency)
        self.zAxisSinglePlotOptions.scale_changed.connect(plotController.update_zScale)
        self.amplAxisSpec3d_options.to_changed.connect(plotController.update_zSlice)
        self.singleSpectrogram_button.clicked["bool"].connect(self.zAxis_l_2.setVisible)
        self.freqAxisSpec3d_options.from_changed.connect(plotController.update_ySlice)
        self.progressionVarTime_options.scale_changed.connect(plotController.update_yScale)
        self.plotSettingsTabs.currentChanged.connect(plotController.plotMode_select)
        self.xAxisSinglePlotOptions.variable_changed.connect(plotController.update_xVar)
        self.zAxisSinglePlotOptions.to_changed.connect(plotController.update_zSlice)
        self.updatePlot_button.released.connect(plotController.on_updatePlot)
        self.param1ValSelect_dd.currentIndexChanged.connect(plotController.select_single_param1)
        self.xAxisGridPlotOptions.scale_changed.connect(plotController.update_xScale)
        self.progressionVarTime_options.variable_changed.connect(plotController.update_xVar)
        self.phase2d_button.clicked["bool"].connect(self.zAxis_l_2.setVisible)
        self.zAxisGridPlotOptions.scale_changed.connect(plotController.update_zScale)
        self.paramAxisSpec3d_options.from_changed.connect(plotController.update_xSlice)
        self.timeAxis3d_options.from_changed.connect(plotController.update_ySlice)
        self.phase2d_button.clicked["bool"].connect(self.zAxisSinglePlotOptions.setVisible)
        self.zAxisGridPlotOptions.variable_changed.connect(plotController.update_zVar)
        self.paramAxisSpec3d_options.variable_changed.connect(plotController.update_xVar)
        self.yAxisSinglePlotOptions.to_changed.connect(plotController.update_ySlice)
        self.yAxisSinglePlotOptions.scale_changed.connect(plotController.update_yScale)
        self.xAxisSinglePlotOptions.scale_changed.connect(plotController.update_xScale)
        self.zAxisGridPlotOptions.from_changed.connect(plotController.update_zSlice)
        self.xAxisGridPlotOptions.to_changed.connect(plotController.update_xSlice)
        self.yAxisGridPlotOptions.variable_changed.connect(plotController.update_yVar)
        self.timeAxis3d_options.scale_changed.connect(plotController.update_yScale)
        self.zAxisSinglePlotOptions.from_changed.connect(plotController.update_zSlice)
        self.zAxisSinglePlotOptions.variable_changed.connect(plotController.update_zVar)
        self.amplAxisTime3d_options.scale_changed.connect(plotController.update_zScale)
        self.param1Animate_button.released.connect(plotController.animate_param1_singleSet)
        self.plot_state_grid3D.currentTextChanged.connect(plotController.update_state_to_plot)
        self.plot_state_spec3D.currentTextChanged.connect(plotController.update_state_to_plot)
        self.plot_state_time3D.currentTextChanged.connect(plotController.update_state_to_plot)

        self.plotSettingsTabs.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(plotController)
    # setupUi

    def retranslateUi(self, plotController):
        plotController.setWindowTitle(QCoreApplication.translate("plotController", u"Form", None))
        self.action1x.setText(QCoreApplication.translate("plotController", u"1x", None))
        self.plot_state_grid3D_l.setText(QCoreApplication.translate("plotController", u"State to plot:", None))
        self.xAxis_l.setText(QCoreApplication.translate("plotController", u"X axis", None))
        self.xAxisGridPlotOptions.setProperty("varDdItems", [
            QCoreApplication.translate("plotController", u"Parameter 1", None),
            QCoreApplication.translate("plotController", u"Parameter 2", None)])
        self.yAxis_l.setText(QCoreApplication.translate("plotController", u"Y axis", None))
        self.yAxisGridPlotOptions.setProperty("varDdItems", [
            QCoreApplication.translate("plotController", u"Parameter 1", None),
            QCoreApplication.translate("plotController", u"Parameter 2", None)])
        self.zAxis_l.setText(QCoreApplication.translate("plotController", u"Z axis", None))
        self.zAxisGridPlotOptions.setProperty("varDdItems", [
            QCoreApplication.translate("plotController", u"PSD at selected frequency", None),
            QCoreApplication.translate("plotController", u"FFT phase at selected frequency", None),
            QCoreApplication.translate("plotController", u"RMS amplitude", None)])
        self.frequency_l.setText(QCoreApplication.translate("plotController", u"Frequency", None))
        self.updatePlot_button.setText(QCoreApplication.translate("plotController", u"Update Plot", None))
        self.plotSettingsTabs.setTabText(self.plotSettingsTabs.indexOf(self.plot3d_tab), QCoreApplication.translate("plotController", u"3D Grid", None))
#if QT_CONFIG(tooltip)
        self.plotSettingsTabs.setTabToolTip(self.plotSettingsTabs.indexOf(self.plot3d_tab), QCoreApplication.translate("plotController", u"Plot a three-dimensional surface of selected results", None))
#endif // QT_CONFIG(tooltip)
        self.plot_state_time3D_l.setText(QCoreApplication.translate("plotController", u"State to plot:", None))
        self.paramAxis_l.setText(QCoreApplication.translate("plotController", u"Parameter axis", None))
        self.progressionVarTime_options.setProperty("varDdItems", [
            QCoreApplication.translate("plotController", u"Parameter 1", None)])
        self.timeAxis_l.setText(QCoreApplication.translate("plotController", u"Time axis", None))
        self.timeAxis3d_options.setProperty("varDdItems", [
            QCoreApplication.translate("plotController", u"Time", None)])
        self.amplAxis_l.setText(QCoreApplication.translate("plotController", u"Amplitude axis", None))
        self.amplAxisTime3d_options.setProperty("varDdItems", [
            QCoreApplication.translate("plotController", u"Signal Amplitude", None)])
        self.fixedParamTime_l.setText(QCoreApplication.translate("plotController", u"Fixed Parameter", None))
        self.fixedParamTimeAnimate_button.setText(QCoreApplication.translate("plotController", u"Animate", None))
        self.updatePlot_button_2.setText(QCoreApplication.translate("plotController", u"Update Plot", None))
        self.plotSettingsTabs.setTabText(self.plotSettingsTabs.indexOf(self.timeHistory3D_tab), QCoreApplication.translate("plotController", u"3D Time", None))
        self.plot_state_spec3D_2.setText(QCoreApplication.translate("plotController", u"State to plot:", None))
        self.paramAxisSpec_l.setText(QCoreApplication.translate("plotController", u"Parameter axis", None))
        self.paramAxisSpec3d_options.setProperty("varDdItems", [
            QCoreApplication.translate("plotController", u"Parameter 1", None),
            QCoreApplication.translate("plotController", u"Parameter 2", None),
            ""])
        self.freqAxisSpec3d_l.setText(QCoreApplication.translate("plotController", u"Frequency axis", None))
        self.freqAxisSpec3d_options.setProperty("varDdItems", [
            QCoreApplication.translate("plotController", u"Frequency", None)])
        self.amplAxisSpec3d_l.setText(QCoreApplication.translate("plotController", u"Amplitude axis", None))
        self.amplAxisSpec3d_options.setProperty("varDdItems", [
            QCoreApplication.translate("plotController", u"PSD Magnitude", None),
            QCoreApplication.translate("plotController", u"FFT Phase", None)])
        self.fixedParamSpec_l.setText(QCoreApplication.translate("plotController", u"Fixed Parameter", None))
        self.fixedParamSpecAnimate_button.setText(QCoreApplication.translate("plotController", u"Animate", None))
        self.updatePlot_button_3.setText(QCoreApplication.translate("plotController", u"Update Plot", None))
        self.plotSettingsTabs.setTabText(self.plotSettingsTabs.indexOf(self.spectrogram3d_tab), QCoreApplication.translate("plotController", u"3D Spectrum", None))
        self.singlePlotStyle_box.setTitle(QCoreApplication.translate("plotController", u"Plot Style", None))
        self.singleSpectrogram_button.setText(QCoreApplication.translate("plotController", u"Spectrogram", None))
        self.singleTimeDomain_button.setText(QCoreApplication.translate("plotController", u"Time-domain", None))
        self.phase2d_button.setText(QCoreApplication.translate("plotController", u"2D Phase Diagram", None))
        self.phase3d_button.setText(QCoreApplication.translate("plotController", u"3D Phase Diagram", None))
        self.zAxisSinglePlotOptions.setProperty("varDdItems", [])
        self.param1Select_l.setText(QCoreApplication.translate("plotController", u"Parameter 1:", None))
        self.param1Animate_button.setText(QCoreApplication.translate("plotController", u"Animate", None))
        self.yAxisSinglePlotOptions.setProperty("varDdItems", [])
        self.zAxis_l_2.setText(QCoreApplication.translate("plotController", u"Z axis", None))
        self.xAxis_l_2.setText(QCoreApplication.translate("plotController", u"X axis", None))
        self.xAxisSinglePlotOptions.setProperty("varDdItems", [])
        self.yAxis_l_2.setText(QCoreApplication.translate("plotController", u"Y axis", None))
        self.Param2Select_l.setText(QCoreApplication.translate("plotController", u"Parameter 2:", None))
        self.param2Animate_button.setText(QCoreApplication.translate("plotController", u"Animate", None))
        self.updatePlot_button_4.setText(QCoreApplication.translate("plotController", u"Update Plot", None))
        self.plotSettingsTabs.setTabText(self.plotSettingsTabs.indexOf(self.plotSingle_tab), QCoreApplication.translate("plotController", u"Single Dataset", None))
#if QT_CONFIG(tooltip)
        self.plotSettingsTabs.setTabToolTip(self.plotSettingsTabs.indexOf(self.plotSingle_tab), QCoreApplication.translate("plotController", u"Plot a single dataset in two dimensions", None))
#endif // QT_CONFIG(tooltip)
    # retranslateUi

